name: Cloudfront & WAF Deployment

on:
  workflow_dispatch:
    inputs:
      deployment:
        type: choice
        description: DeployOrTearDown
        options:
          - Apply
          - Destroy

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 1
    
        - uses: hashicorp/setup-terraform@v2

        - name: init
          run: terraform init

        - name: validate
          run: terraform validate

        - name: plan
          run: terraform plan

        - name: apply or destroy
          run: |
            if [ ${{ github.event.inputs.deployment }} == 'Apply' ]; then  
              terraform apply -var 'api_gateway_arn=${{ vars.API_GATEWAY_UPLOAD_IMAGES_ARN }}' -auto-approve
            elif [ ${{ github.event.inputs.deployment }} == 'Destroy' ]; then  
              terraform destroy -auto-approve
            fi
          shell: bash

        - name: Push Cloudfront url to organization variables
          run: |
            if [ ${{ github.event.inputs.deployment }} == 'Apply' ]; then  
              cat cloudfront_domain_name.dat
              source cloudfront_domain_name.dat
              curl -L -X PATCH -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $ACCESS_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/orgs/friends-ce-3-group/actions/variables/CLOUDFRONT_DOMAIN_NAME -d '{"name":"CLOUDFRONT_DOMAIN_NAME","value":"'$CLOUDFRONT_DOMAIN_NAME'","visibility":"all"}'
            elif [ ${{ github.event.inputs.deployment }} == 'Destroy' ]; then
              curl -L -X PATCH -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $ACCESS_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/orgs/friends-ce-3-group/actions/variables/CLOUDFRONT_DOMAIN_NAME -d '{"name":"CLOUDFRONT_DOMAIN_NAME","value":"DESTROYED","visibility":"all"}'
            fi
